### ISSUE TITLE
Question regarding Evaluation?

### ISSUE THREAD

**Issue by Itaymanes** [mattiasegu/uncertainty_estimation_deep_learning#1]
I was trying to follow your code and article that you have published.
However, when I download the data from Udacity, the HMB_3 files (the test data) do not have the truth ground steering angle. 
Thus, I was wondering how to evaluate the results and the variances as well? Do you have the ground truth and I downloaded the wrong files? or did you neglect the ground truth for evaluating the variance?

I am quite confused upon this point.

**Comment by mattiasegu** [comment]
Hi @Itaymanes, thanks for your interest in our project!

If you download the data as explained in the previous README, you should find also the ground truth for the steering angles. However, you shouldn't expect to find also the ground truth for variance estimates. As explained in the paper, one of the main challenges when developing methods to estimate uncertainty in deep learning is that usually the ground truth for the uncertainty is not provided. This is why we evaluate our uncertainty estimates using the log-likelihood :)

Moreover, to make our framework easier to use for the community we have now switched this repository to a new task: classification on CIFAR10. If you want to try this new version of the repository, you will find out that you don't have to worry about data loading anymore!

Let me know if you still have any problem.
