### ISSUE TITLE
Evaluation with pre-trained model crashes when running on CPU

### ISSUE THREAD

**Issue by marbakken** [mattiasegu/uncertainty_estimation_deep_learning#5]
I got some errors when trying to run the evaluation code on CPU. 

Here are the error messages I got:
Issue 1: Error when trying to run on the CPU."RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU."

Issue 2: Error when loading the checkpoint file of the pre-trained model: "RuntimeError: Error(s) in loading state_dict for ResNetADFDropout: Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", ....."

The first one is easy to fix, but the second one is related to how the model was saved. The topic is disussed here: [(https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686)]
The best solution is probably to save the model without the "module" name included. See my pull request for a preliminary solution for existing checkpoints.

**Comment by mattiasegu** [comment]
Thank you very much for the contribution @marbakken ! It might be a bit hacky, but for now it's what most users need. I am merging your pull request and I will fix the issue with the module prefix later on. Thanks again.
