### ISSUE TITLE
Quick question related to the output of the framework

### ISSUE THREAD

**Issue by mflova** [mattiasegu/uncertainty_estimation_deep_learning#6]
Currently I am having some doubts related to the output of the framework that maybe is decresing the efficiency of my network.
I am not sure about how the total uncertainty of the network is expressed. In your paper (see equation 16), it refers to the "total variance" of the network (model + data) but it is also named as σ_total, which seems a little bit confusing to me.

If I understood well, "outputs_variance (line 236)" equals to σ_total from the paper.
In terms of modelling the output as a normal distribution, is σ_total equal to its sigma value? Or do we have to calculate the square root of σ_total?

Finally, when calling the function compute_log_likelihood (eval.py, 242 line), the input used is "outputs_variance", but this function then uses it as sigma (σ). Does this mean we have to calculate the square root of this value before calling compute_log_likelihood?

I am sorry for the inconveniences, I guess this is not the best place to post this.
Thank you in davance.

**Comment by mattiasegu** [comment]
That is correct, I updated the eval.py script accordingly! Thanks for letting me know and sorry for the very very late reply :)
